encryptionsalt: v1:p902WfkaBvw=:v1:9Nsk3a2nmpKTvtVv:cHXH9ijUsa08f96kZ7hJJHI2s1ZBbA==
config:
  blogs:POSTGRES_DB: blogs
  blogs:POSTGRES_HOST: db_service
  blogs:POSTGRES_PORT: "5432"
  blogs:APPLICATION_PORT: "8080"
  blogs:POSTGRES_USER:
    secure: v1:+6Wv7HEFET/4bniv:Xva+m/2XE3RHS/dSlWZe1JcPfABDZsQH
  blogs:POSTGRES_PASSWORD:
    secure: v1:cRC5J8lzAVSJBOcj:QyB6iFKOkR4NSmA28tkYpTJYtywh
