name: kubernetes
description: A TypeScript program to deploy a web application onto a Kubernetes cluster
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: webapp-kubernetes-typescript
