encryptionsalt: v1:6Te5S7+TaSc=:v1:tUCCmeMoTsU7vvgz:V6pl+VwnJIJIswz55/j3FOhCHkJ8JA==
config:
  blogs:POSTGRES_DB: blogs
  blogs:POSTGRES_HOST: blogdb
  blogs:POSTGRES_PORT: "5432"
  blogs:APPLICATION_PORT: "8080"
  blogs:POSTGRES_USER:
    secure: v1:Sk1TldFQYSYq5gnA:pJJPzmORzqiGwQsG7veU1HJ2fRd6V557
  blogs:POSTGRES_PASSWORD:
    secure: v1:yWPbng3K0hl5iwAc:K6nCx7RM8v2kJ4cOlZs4XfJGtBkq
